#! /bin/sh

#
# Copyright (C) 2007, 2008 Francesco Salvestrini
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

# Test to ensure that parsing of lkc configuration is working
# Report from Francesco Salvestrini

. $testdir/defs || exit 1

cat > ./choose.ct <<EOF
if ARCH_CLPS711X

menu "CLPS711X/EP721X Implementations"

config ARCH_AUTCPU12
	bool "AUTCPU12"
	help
	  Say Y if you intend to run the kernel on the autronix autcpu12
	  board. This board is based on a Cirrus Logic CS89712.

endmenu

endif
EOF

$CHOICETOOL -i ./choose.ct || exit 1

exit 0
