#! /bin/sh

#
# Copyright (C) 2007, 2008 Francesco Salvestrini
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

# Test to ensure that parsing of lkc configuration is working
# Report from Francesco Salvestrini

. $testdir/defs || exit 1

cat > ./choose.ct <<EOF
if ARCH_H720X

menu "h720x Implementations"

config ARCH_H7201
	bool "gms30c7201"
	depends on ARCH_H720X
	select CPU_H7201
	help
	  Say Y here if you are using the Hynix GMS30C7201 Reference Board

config ARCH_H7202
	bool "hms30c7202"
	select CPU_H7202
	depends on ARCH_H720X
	help
	  Say Y here if you are using the Hynix HMS30C7202 Reference Board

endmenu

config CPU_H7201
	bool
	help
	  Select code specific to h7201 variants

config CPU_H7202
	bool
	help
	  Select code specific to h7202 variants
config H7202_SERIAL23
	depends on CPU_H7202
	bool "Use serial ports 2+3"
	help
	  Say Y here if you wish to use serial ports 2+3. They share their
	  pins with the keyboard matrix controller, so you have to decide.


endif
EOF

$CHOICETOOL -i ./choose.ct || exit 1

exit 0
